<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Authors>Domagoj Piškur</Authors>
    <RepositoryUrl>https://github.com/dopiskur/scaleTrigger</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.10" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
    <PackageReference Include="Polly.Core" Version="8.7.0" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.5" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
    <PackageReference Include="MySqlConnector" Version="2.6.1" />
    <PackageReference Include="Azure.Identity" Version="1.21.0" />
  </ItemGroup>

</Project>
